django_auth_request_ldap/auth_request/urls.py
from django.conf.urls import include, url
from .views import check_auth, check_auth_info
from django.contrib.auth.views import login

urlpatterns = [
    url(r'^$',                          check_auth, name='auth-check'),
    url(r'^info/$',                     check_auth_info, name='auth-info'),
    url(r'^info/(?P<zone_name>[-\w]+)/$', check_auth_info, name='named-auth-info'),
    url(r'^login/$',                    login, {'template_name': "auth_request/login.html"}, name='login'),
]

django_auth_request_ldap/django_auth_request_ldap/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^select2/', include('django_select2.urls')),
    url(r'^auth_request/', include('auth_request.urls', namespace="auth_request")),
]

django_auth_request_ldap/auth_request/models.py
from django.conf import settings
from django.core.cache import cache
from django.db import models
from django.utils import timezone
from django.utils.encoding import python_2_unicode_compatible, force_text
from django.utils.translation import ugettext_lazy as _

from operator import attrgetter

from .enums import (ZONE_ACCESS_DEFAULT, ZONE_ACCESS_ALLOWED, ZONE_ACCESS_DENIED, ZONE_ACCESS, ZONE_ACCESS_DISPLAY,
                    ACTION_ACCESS, ACTION_DENIED, ACTION_LOGIN, ACTION_LOGOUT, ACTION_DISABLED, ACTION_UNKNOWN,
                    ACCESS_DISPLAY)

import time

import logging
logger = logging.getLogger(__name__)

ZONE_ACCESS_CACHE_TIME = getattr(settings, "ZONE_ACCESS_CACHE_TIME", 0)
ZONE_ACCESS_LOG_CACHED = getattr(settings, "ZONE_ACCESS_LOG_CACHED", 0)
ZONE_ACCESS_DEFAULT_RESPONSE = getattr(settings, "ZONE_ACCESS_DEFAULT_RESPONSE", ZONE_ACCESS_DENIED)


class AccessMatrix(object):
    def __init__(self, zone, user, group_rules, user_rules):
        self.zone = zone
        self.user = user
        self.group_rules = group_rules
        self.user_rules = user_rules

    @property
    def user_pk(self):
        return self.user.pk if self.user.is_authenticated() else 0

    def _cache_matrix(self, key, rules):
        key = '_cache_matrix_%d_%d_%s' % (self.zone.pk, self.user_pk, key)
        if ZONE_ACCESS_CACHE_TIME:
            data = cache.get(key, None)
            if data is not None:
                setattr(self, key, data[0])
                return data
        data = getattr(self, key, None)
        if data is not None:
            return data, None
        data = self.process_rules(rules)
        setattr(self, key, data)
        if ZONE_ACCESS_CACHE_TIME:
            cache.set(key, (data, time.time()), ZONE_ACCESS_CACHE_TIME)
        return data, None

    @property
    def rules(self):
        return self.group_rules + self.user_rules

    def process_rules(self, rules):
        print("process_rules")
        rules = sorted(rules, key=attrgetter("order"))
        access = self.zone.access
        logger.debug("Default access for matrix: %s", ZONE_ACCESS_DISPLAY[access])
        for rule in rules:
            if rule.access != ZONE_ACCESS_DEFAULT:
                access = rule.access
            logger.debug(
                "%d: Applied rule for %s %s: %s, new active access: %s",
                rule.order,
                rule.object.__class__.__name__,
                rule.object,
                ZONE_ACCESS_DISPLAY[rule.access],
                ZONE_ACCESS_DISPLAY[access]
            )
        logger.debug("Done processing access: %s", ZONE_ACCESS_DISPLAY[access])
        return access

    @property
    def allowed(self):
        return self._cache_matrix('all', self.rules)

    @property
    def allowed_by_group(self):
        return self._cache_matrix('group', self.group_rules)

    @property
    def allowed_by_user(self):
        return self._cache_matrix('user', self.user_rules)

    def __bool__(self):
        return self.allowed
    __nonzero__ = __bool__

    def __repr__(self):
        return "<AccessMatrix: %r: %r>" % (self.zone, self.user)


@python_2_unicode_compatible
class Zone(models.Model):
    name = models.CharField(max_length=128)
    code = models.SlugField(max_length=128)
    access = models.IntegerField(_("access"), choices=ZONE_ACCESS, default=ZONE_ACCESS_DEFAULT)
    enabled = models.BooleanField(default=True)

    def for_user(self, user):
        if not user.is_authenticated():
            return AccessMatrix(self, user, [], [])
        groups = user.groups.all()
        group_rules = list(self.groups.filter(group_id__in=[g.pk for g in groups]))
        user_rules = list(self.users.filter(user=user))
        return AccessMatrix(self, user, group_rules, user_rules)

    @classmethod
    def process_request(self, user, zone_key):
        if not user.is_authenticated():
            user_pk = 0
        else:
            user_pk = user.pk
        key = 'process_%s_%s' % (zone_key, user_pk)

        if ZONE_ACCESS_CACHE_TIME:
            data = cache.get(key, None)
            if data is not None:
                return data

        try:
            zone = Zone.objects.get(code=zone_key)
        except Zone.DoesNotExist:
            return ACTION_UNKNOWN, None

        data = zone.process(user)

        if ZONE_ACCESS_CACHE_TIME:
            cache.set(key, (data, time.time()), ZONE_ACCESS_CACHE_TIME)
        return data, None

    def do_log(self, matrix, action):
        allowed, cached_at = matrix.allowed
        user_pk = matrix.user_pk
        key = 'do_log_%s_%s_%s' % (user_pk, matrix.zone.pk, allowed)
        username = "<ANONYMOUS>" if user_pk == 0 else getattr(matrix.user, matrix.user.USERNAME_FIELD)
        if ZONE_ACCESS_LOG_CACHED:
            if cache.get(key, None):
                return
            cache.set(key, True, ZONE_ACCESS_LOG_CACHED)
        logger.info("request to zone '%s' resulted in '%s'(%s) / '%s'(%s) for user '%s'(%d)",
                    self.code,
                    ZONE_ACCESS_DISPLAY[allowed],
                    allowed,
                    ACCESS_DISPLAY[action],
                    action,
                    username,
                    user_pk,
                    )

    def process(self, user):
        if not self.enabled:
            return ACTION_DISABLED

        matrix = self.for_user(user)

        def _log(action):
            self.do_log(matrix, action)
            return action

        access, cached_at = matrix.allowed
        if access == ZONE_ACCESS_DEFAULT:
            access = ZONE_ACCESS_DEFAULT_RESPONSE

        if access == ZONE_ACCESS_DENIED:
            if not user.is_authenticated():
                return _log(ACTION_LOGIN)
            return _log(ACTION_DENIED)

        if access == ZONE_ACCESS_DENIED:
            return _log(ACTION_DENIED)

        return _log(ACTION_ACCESS)

    def __str__(self):
        return self.name


@python_2_unicode_compatible
class ZoneUser(models.Model):
    zone = models.ForeignKey(Zone, related_name="users")
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="+")
    access = models.IntegerField(_("access"), choices=ZONE_ACCESS, default=ZONE_ACCESS_DEFAULT)
    order = models.IntegerField(_("order of importance"), default=10)

    @property
    def object(self):
        return self.user

    class Meta:
        ordering = ['order']

    def __repr__(self):
        return "<%s: %r (%s)>" % (self.__class__.__name__, self.user, ZONE_ACCESS_DISPLAY.get(self.access))

    def __str__(self):
        return force_text(self.user)


@python_2_unicode_compatible
class ZoneGroup(models.Model):
    zone = models.ForeignKey(Zone, related_name="groups")
    group = models.ForeignKey(settings.AUTH_GROUP_MODEL, related_name="+")
    access = models.IntegerField(_("access"), choices=ZONE_ACCESS, default=ZONE_ACCESS_DEFAULT)
    order = models.IntegerField(_("order of importance"), default=10)

    @property
    def object(self):
        return self.group

    class Meta:
        ordering = ['order']

    def __repr__(self):
        return "<%s: %r (%s)>" % (self.__class__.__name__, self.group, ZONE_ACCESS_DISPLAY.get(self.access))

    def __str__(self):
        return force_text(self.group)

django_auth_request_ldap/auth_request/views.py
from django.conf import settings
from django.core.urlresolvers import reverse
# Avoid shadowing the login() and logout() views below.
from django.contrib.auth import REDIRECT_FIELD_NAME, login as auth_login
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import resolve_url
from django.template.response import TemplateResponse
from django.utils.http import is_safe_url
from django.utils.six.moves.urllib.parse import urlencode
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.debug import sensitive_post_parameters

from .models import Zone
from .forms import ZoneAuthenticationForm

from .enums import ACTION_ACCESS, ACTION_DENIED, ACTION_LOGIN, ACTION_DISABLED, ACTION_UNKNOWN, ACCESS_DISPLAY


def get_response(request, response_type=HttpResponse, *args, **kwargs):
    user = request.user
    resp = response_type(*args, **kwargs)
    if user.is_authenticated():
        resp['X-Zone-Username'] = getattr(user, user.USERNAME_FIELD)
        resp['X-Zone-Email'] = user.email
        resp['X-Zone-Userid'] = user.pk
        resp['X-Zone-First-Name'] = user.first_name
        resp['X-Zone-Last-Name'] = user.last_name
    else:
        resp['X-Zone-Username'] = ""
        resp['X-Zone-Email'] = ""
        resp['X-Zone-Userid'] = 0
        resp['X-Zone-First-Name'] = ""
        resp['X-Zone-First-Name'] = ""
    resp['X-Zone-SID'] = request.session.session_key
    return resp


def check_auth(request, zone_name=None):
    redirect_to = request.META.get('HTTP_X_ORIGINAL_URI', '')
    if not zone_name:
        zone_name = request.META.get('HTTP_X_ZONE_NAME', 'default')

    access, cached = Zone.process_request(request.user, zone_name)

    if access == ACTION_ACCESS:
        resp = get_response(request)
        resp.status_code = 200
    elif access == ACTION_LOGIN:
        url_parts = urlencode({
            REDIRECT_FIELD_NAME: redirect_to,
        })
        resp = get_response(request, HttpResponseRedirect, "%s?%s" % (reverse('auth_request:login'), url_parts))
    elif access in (ACTION_DENIED, ACTION_DISABLED, ACTION_UNKNOWN):
        resp = get_response(request)
        resp.status_code = 403
    return resp


def check_auth_info(request, zone_name=None, template_name="auth_request/info.html"):
    if not request.user.is_superuser or request.GET.get('apply'):
        return check_auth(request, zone_name)

    redirect_to = request.META.get('HTTP_X_ORIGINAL_URI', '')
    if not zone_name:
        zone_name = request.META.get('HTTP_X_ZONE_NAME', 'default')

    access, cached = Zone.process_request(request.user, zone_name)

    try:
        zone = Zone.objects.get(code=zone_name)
        grouprules = list(zone.groups.all().prefetch_related('group'))
        userrules = list(zone.users.all().prefetch_related('user'))
    except Zone.DoesNotExist:
        zone = None
        grouprules = []
        userrules = []

    context = {
        'access': access,
        'access_display': ACCESS_DISPLAY[access],
        'cached': cached,
        'zone_name': zone_name,
        'zone': zone,
        'redirect_to': redirect_to,

        'grouprules': grouprules,
        'userrules': userrules,
    }

    return TemplateResponse(request, template_name, context)


@sensitive_post_parameters()
@csrf_protect
@never_cache
def login(request, zone=None, template_name="auth_request/login.html",
          redirect_field_name=REDIRECT_FIELD_NAME,
          authentication_form=ZoneAuthenticationForm,
          current_app=None, extra_context=None):
    """
    Displays the login form and handles the login action.
    """
    redirect_to = request.POST.get(redirect_field_name,
                                   request.GET.get(redirect_field_name, ''))

    if request.method == "POST":
        form = authentication_form(request, data=request.POST)
        if form.is_valid():

            # Ensure the user-originating redirection url is safe.
            if not is_safe_url(url=redirect_to, host=request.get_host()):
                redirect_to = resolve_url(settings.LOGIN_REDIRECT_URL)

            # Okay, security check complete. Log the user in.
            auth_login(request, form.get_user())
            return HttpResponseRedirect(redirect_to)
    else:
        form = authentication_form(request)

    context = {
        'form': form,
        redirect_field_name: redirect_to,
    }
    if extra_context is not None:
        context.update(extra_context)

    if current_app is not None:
        request.current_app = current_app

    return TemplateResponse(request, template_name, context)

django_auth_request_ldap/auth_request/templates/auth_request/info.html
{% extends "admin/login.html" %}
{% load i18n admin_static suit_tags %}

{% block extrastyle %}
<style>
.uneditable-input {
    cursor: default;
    color: #000;
}
</style>
{% endblock %}

{% block content %}
<div id="content-main" style="width: 540px; margin-left: -270px; top: 25%;">
    <h1><i class="icon-globe icon-white"></i> {% firstof zone.name zone_name %}</h1>
    <form class="form-horizontal" style="margin-top: 0px">
        <div class="form-row control-group">
            <label class="control-label">Zone Name:</label><span class="input-xlarge uneditable-input">{% firstof zone.name "Unknown Zone" %}</span>
        </div>
        <div class="form-row control-group">
            <label class="control-label">Calculated Access:</label><span class="input-xlarge uneditable-input">{{access_display}}</span>
        </div>
{% if redirect_to %}
        <div class="form-row control-group">
            <label class="control-label">Redirect To:</label><span class="input-xlarge uneditable-input">{{redirect_to}}</span>
        </div>
{% endif %}
{% if grouprules or userrules %}
        <h2>Applied rules</h2>
        <div class="form-row control-group">
            <label class="control-label">Default access:</label><span class="input-xlarge uneditable-input">{{zone.get_access_display}}</span>
        </div>
{% if grouprules %}
        <h3>Group rules</h3>
    {% for grule in grouprules %}
        <div class="form-row control-group">
            <label class="control-label">{{grule.order}}: {{grule.group}}</label><span class="input-xlarge uneditable-input">{{grule.get_access_display}}</span>
        </div>
    {% endfor %}
{% endif %}
{% if userrules %}
        <h3>User rules</h3>
    {% for urule in userrules %}
        <div class="form-row control-group">
            <label class="control-label">{{urule.order}}: {{urule.group}}</label><span class="input-xlarge uneditable-input">{{urule.get_access_display}}</span>
        </div>
    {% endfor %}
{% endif %}
{% endif %}
        <div class="submit-row">
            <a href="?apply=1" class="btn btn-primary">Execute</a>
        </div>
    </form>
</div>
{% endblock content %}

{% block footer %}{% endblock footer %}

django_auth_request_ldap/auth_request/templates/auth_request/login.html
{% extends "admin/login.html" %}
{% load i18n admin_static suit_tags %}

{% block content %}

    {% if form.errors and not form.non_field_errors and not form.this_is_the_login_form.errors %}
        <p class="errornote alert alert-error">
            {% blocktrans count counter=form.errors.items|length %}Please correct the error below.{% plural %}Please correct the errors below.{% endblocktrans %}
        </p>
    {% endif %}

    {% if form.non_field_errors or form.this_is_the_login_form.errors %}
        {% for error in form.non_field_errors|add:form.this_is_the_login_form.errors %}
            <p class="errornote alert alert-error">
                {{ error }}
            </p>
        {% endfor %}
    {% endif %}

    <div id="content-main">
        <h1><i class="icon-lock icon-white"></i> {% trans 'Login required' %}</h1>

        <form action="{{ app_path }}" method="post" id="login-form"><div class="hide">{% csrf_token %}</div>
            <div class="form-row control-group{% if not form.this_is_the_login_form.errors and form.username.errors %} error{% endif %}">
                <label for="id_username" class="control-label required">{{ form.username.label }}:</label> {{ form.username }}
              {% if not form.this_is_the_login_form.errors and form.username.errors %}<div class="help-block">{{ form.username.errors }}</div>{% endif %}
            </div>
            <div class="form-row control-group{% if not form.this_is_the_login_form.errors and form.password.errors %} error{% endif %}">
                <label for="id_password" class="control-label required">{% trans 'Password' %}:</label> {{ form.password }}
              {% if not form.this_is_the_login_form.errors and form.password.errors %}<div class="help-block">{{ form.password.errors }}</div>{% endif %}
                <input type="hidden" name="this_is_the_login_form" value="1"/>
                <input type="hidden" name="next" value="{{ next }}"/>
            </div>
            {% url 'admin_password_reset' as password_reset_url %}
            {% if password_reset_url %}
                <div class="password-reset-link">
                    <a href="{{ password_reset_url }}">{% trans 'Forgotten your password or username?' %}</a>
                </div>
            {% endif %}
            <div class="submit-row">
                <input type="submit" value="{% trans 'Log in' %}" class="btn btn-info"/>
            </div>
        </form>

        <script type="text/javascript">
            document.getElementById('id_username').focus()
        </script>
    </div>
{% endblock %}

{% block footer %}{% endblock footer %}